// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdHk6NZ-inMMpiSERXqxyLoaBRiXGHW7s',
    appId: '1:183350722206:web:af6177743d3de5b7fe458f',
    messagingSenderId: '183350722206',
    projectId: 'flashgenius-d4ec3',
    authDomain: 'flashgenius-d4ec3.firebaseapp.com',
    storageBucket: 'flashgenius-d4ec3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlHkKr60DlFy5_Cve-ROrsjCCcDsT9tUo',
    appId: '1:183350722206:android:4d5ef04037232a55fe458f',
    messagingSenderId: '183350722206',
    projectId: 'flashgenius-d4ec3',
    storageBucket: 'flashgenius-d4ec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hrdm3Sjh-f-Ghtg3-euqmKfmy0c0kFo',
    appId: '1:183350722206:ios:3386a200247e342cfe458f',
    messagingSenderId: '183350722206',
    projectId: 'flashgenius-d4ec3',
    storageBucket: 'flashgenius-d4ec3.firebasestorage.app',
    iosClientId: '183350722206-6hlrdlik7i3j5dj8pvf4eicqfsq1s65i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardApp',
  );
}
